version: '3.8'
services:
  apache:
    container_name: iim_apache
    hostname: iim_apache
    # image: 'httpd:2.4' (search)
    build: ./containers/apache
    ports:
      - 81:80
      - 443:443
  php:
    container_name: iim_php
    hostname: iim_php
    build: ./containers/php